#########################
## Sass Lint Options File
#########################
# Linter Options
options:
  merge-default-rules: true
rules:
  no-trailing-whitespace:
   - 2
  class-name-format:
    - 2
    - 
      convention: hyphenatedbem
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 0
    -
      exclude:
        - breakpoint
        - mq
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 2
    -
      order:
        - display
        - margin
